### ISSUE TITLE
Parameters for Data Fields 

### ISSUE THREAD

**Issue by TawsifTorabi** [shshohagh/steadfast-courier#1]
What are the parameters for the data fields? It's unclear. Would someone be able to help me with that?

**Comment by shshohagh** [comment]
'invoice',
                        'recipient_name',
                        'recipient_address',
                        'recipient_phone',
                        'cod_amount',
                        'note'

**Comment by TawsifTorabi** [comment]
Hey, Thanks, Btw I got the API Documentation, can I contribute to your repo with a module for steadfast to use in Codeigniter?

**Comment by shshohagh** [comment]
yes
